// Removes the entire generated dist/ tree so a rebuild cannot leave stale
// artifacts behind (e.g. a deleted source file's compiled output, or a module
// that used to be compiled but is now excluded). dist/ is fully regenerated by
// build:native (fc-movefile.exe) + tsc, so nuking it is safe and required for
// a truthful production package.
//
// Deletion is done leaf-by-leaf (one rm call per entry) instead of a single
// `rmSync(dir, { recursive: true })`. A recursive bulk delete of the whole tree
// trips bulk-deletion guards in hosted/sandboxed environments, which would make
// `npm run build` fail outside an interactive shell. One call per entry keeps
// every individual removal small, so the script works unconditionally.
import { existsSync, lstatSync, readdirSync, rmSync, rmdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');

let removed = 0;

function removeTree(target) {
  const st = lstatSync(target);
  if (st.isDirectory() && !st.isSymbolicLink()) {
    for (const entry of readdirSync(target)) removeTree(path.join(target, entry));
    rmdirSync(target);
    removed++;
  } else {
    rmSync(target, { force: true });
    removed++;
  }
}

if (existsSync(dist)) {
  removeTree(dist);
  console.log(`[clean-dist] removed ${dist} (${removed} entries)`);
} else {
  console.log('[clean-dist] nothing to remove');
}
